<h1, align=center> &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;数据科学引论 - Python之道 </h1>

<h1, align=center> &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;第4课 数据分析入门 </h1>

<hr>

### 目录 
[**Numpy 库**](#NumPy-库)   
[**Pandas 库**](#Pandas-库)  
[**按国家和年份统计的CO2排放量**](#按国家和年份统计的CO2排放量)  
[**获取数据**](#获取数据)  
[**使用Pandas导入数据**](#使用-Pandas-导入数据)  
[**Dataframe的特性**](#Dataframe-的特性)  
[**对Dataframe求子集**](#对-Dataframe-求子集)  
[**按照条件求子集**](#按照条件求子集)  





<hr>

<h1, align="center">NumPy 库</h1>
__NumPy__: 
- 快速
- 多维数组 
- 向量化计算


### NumPy 多维数组
多维数组对象.  
用来在整块数据上执行数学操作. 

In [1]:
# to insert a library (a file consisting of Python code) use "import"
import numpy as np

#### 创建多维数组
- 使用 __array__ 函数.  
- 所有元素必须具有 __相同类型__ (同构)

In [ ]:
data=np.array([[ 1.9526, -0.246 , -0.8856],
[ 0.5639, 0.2379, 0.9104]])
data

每个数组都具有 __维数__ 和 __形状__ (一个表示每个维度尺寸的元素)

In [ ]:
data.ndim

In [ ]:
data.shape

__dtype:__ 描述数组的数据类型的对象:


In [ ]:
data.dtype

__empty__, __arange__ , __zeros__ 和 **ones** 数组

In [ ]:
data1=np.empty((3,2))
data1

In [ ]:
data0=np.zeros(10)
data0

In [ ]:
data3=np.arange(10)
data3

### <span style="color: red">轮到你了:</span> 
创建一个 2x4 的数组，数组中元素都是 1，然后获取该数组的数据类型和形状。

In [ ]:
#You code



#### 数据类型

In [ ]:
data=np.array([1.25, -9.6, 42], dtype=np.string_)
data

可以将该数组强制类型转换为浮点数类型

In [ ]:
data.astype(np.float32)

<hr></hr>
<div class="alert alert-success alertsuccess" style="margin-top: 0px">
<h4> [tip] 强制类型转换后，为什么-9.6变成了-9.60000038？ </h4>
<p></p>
这是因为浮点数只是一种近似表达，它几乎总是会存在误差：
<li>简单地讲，浮点数中每一位都表示2的-n次方，32位浮点数最高精度就是2的-32次方。我们可以这样理解，浮点数的表示机制就是用一系列离散的点来表示连续的数轴，点与点之间的距离就是浮点数最高精度位所能表示的数字。除非希望表示的浮点数正好落在这些点上，否则误差总是存在，它总是会近似地表示成最靠近它的某个点所表示的数字。</li>
<li>回到-9.6的例子，就是因为浮点数机制无法精确表示它，但是在能够精确表示的数字中，-9.60000038离它最近，因此用-9.60000038近似表示它。</li>
<p></p>
浮点数的这种机制告诉我们，需要精确表示数据时，不要使用浮点数。
<li>例如，在表示货币金额时，通常会选择使用整数来表示，单位为分，而不会选择使用浮点数来表示。如果我们留意第三方支付服务的接口，就会发现它们清一色都是使用单位为分的整数来表示的。</li>
<p></p>
</div>
<hr></hr>

### 操作

In [2]:
arr= np.array([[1., 2., 3.], [4., 5., 6.]])
arr

array([[1., 2., 3.],
       [4., 5., 6.]])

#### 算数操作

In [3]:
arr*2

array([[ 2.,  4.,  6.],
       [ 8., 10., 12.]])

In [4]:
arr*arr

array([[ 1.,  4.,  9.],
       [16., 25., 36.]])

<hr></hr>
<div class="alert alert-success alertsuccess" style="margin-top: 0px">
<h4> [tip] **arr*arr**执行的不是矩阵乘法？ </h4>
<p></p>
很遗憾，尽管多维数组看起来就是矩阵，但是**arr*arr**执行的不是矩阵乘法。<br/>
**arr*arr**执行的是将两个矩阵对应位置上元素的乘积作为结果矩阵中对应位置上的元素。所以：
<li>尽管arr是一个2×3的矩阵，按照矩阵乘法的规则，**arr*arr**非法，但是在Python中这是合法操作。</li>
<li>**arr*arr**产生的结果仍旧是一个2×3的矩阵，其中每个元素的值都是arr中对应元素的平方值。</li>
<p></p>
</div>
<hr></hr>

<hr></hr>
<div class="alert alert-success alertsuccess" style="margin-top: 0px">
<h4> [tip] 强制类型转换后，为什么-9.6变成了-9.60000038？ </h4>
<p></p>
这是因为浮点数只是一种近似表达，它几乎总是会存在误差：
<li>简单地讲，浮点数中每一位都表示2的-n次方，32位浮点数最高精度就是2的-32次方。我们可以这样理解，浮点数的表示机制就是用一系列离散的点来表示连续的数轴，点与点之间的距离就是浮点数最高精度位所能表示的数字。除非希望表示的浮点数正好落在这些点上，否则误差总是存在，它总是会近似地表示成最靠近它的某个点所表示的数字。</li>
<li>回到-9.6的例子，就是因为浮点数机制无法精确表示它，但是在能够精确表示的数字中，-9.60000038离它最近，因此用-9.60000038近似表示它。</li>
<p></p>
浮点数的这种机制告诉我们，需要精确表示数据时，不要使用浮点数。
<li>例如，在表示货币金额时，通常会选择使用整数来表示，单位为分，而不会选择使用浮点数来表示。如果我们留意第三方支付服务的接口，就会发现它们清一色都是使用单位为分的整数来表示的。</li>
<p></p>
</div>
<hr></hr>

### 索引和切片
用来选择数据子集或单个元素

In [5]:
arr = np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

与Python的列表相同:

In [6]:
arr[5]

5

In [7]:
arr[5:8]

array([5, 6, 7])

可以将某个值赋给一个切片:

In [8]:
arr[5:8] = 12
arr

array([ 0,  1,  2,  3,  4, 12, 12, 12,  8,  9])

In [9]:
arr[5:]

array([12, 12, 12,  8,  9])

在多维数组中，单个索引对应的元素都不再是具体的值，而是一个数组

In [10]:
arr2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
arr2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [11]:
arr2d[2]

array([7, 8, 9])

In [12]:
arr2d[0][2]   # also: arr2d[0, 2]

3

In [13]:
arr2d[2:]

array([[7, 8, 9]])

切片总是按照先切第0维，再切第1维，以此类推的顺序切。  
例如，下面的代码表示先切出前两行，然后再切出后两列：

In [14]:
arr2d[:2, 1:]

array([[2, 3],
       [5, 6]])

### 布尔索引

In [15]:
data=np.random.rand(7,4)
data

array([[0.51588715, 0.35777413, 0.80723793, 0.7063666 ],
       [0.11894065, 0.03444955, 0.27141597, 0.21443695],
       [0.60629048, 0.37832301, 0.49442049, 0.33967049],
       [0.06040296, 0.21674093, 0.81120018, 0.76226294],
       [0.74253144, 0.7416398 , 0.62609657, 0.65686053],
       [0.29647258, 0.21852444, 0.17064002, 0.01281695],
       [0.55773412, 0.83587397, 0.65037929, 0.61882846]])

In [16]:
data > 0.4    # Comparison Operators: ==, !=, &, |

array([[ True, False,  True,  True],
       [False, False, False, False],
       [ True, False,  True, False],
       [False, False,  True,  True],
       [ True,  True,  True,  True],
       [False, False, False, False],
       [ True,  True,  True,  True]])

In [17]:
data[(data>0.4)]

array([0.51588715, 0.80723793, 0.7063666 , 0.60629048, 0.49442049,
       0.81120018, 0.76226294, 0.74253144, 0.7416398 , 0.62609657,
       0.65686053, 0.55773412, 0.83587397, 0.65037929, 0.61882846])

### 函数

In [18]:
arr = np.arange(5)
np.sqrt(arr)   #squar root function

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ])

In [19]:
np.exp(arr)   #exponentiation function

array([ 1.        ,  2.71828183,  7.3890561 , 20.08553692, 54.59815003])

In [20]:
np.mean(arr) #average function

2.0

### <span style="color: red">轮到你了:</span> 

创建一个3x2的numpy数组 (使用 __ones__ 函数), 然后选择其中的第2行

In [ ]:
## YOUR CODE BELOW




<h1, align="center">Pandas 库</h1>

Pandas
- 可用于大多数类型的数据分析
- 可对结构化或表格化数据进行分析
- 高层数据结构
- 构建在NumPy之上  
- 可进行时间序列操作


对象:  
- Series  
- DataFrame  



首先, 导入Pandas包

In [21]:
import pandas as pd

#### Series

Series是一种类似一维数组的对象，其中包含了一个数据数组(可以具有任何NumPy的数据类型)和一个被称为索引的由数据标号构成的关联数组。

In [22]:
obj2 = pd.Series([4, 7, -5, 3], index=['d', 'b', 'a', 'c'])
obj2

d    4
b    7
a   -5
c    3
dtype: int64

In [23]:
obj2[['c', 'a', 'd']]

c    3
a   -5
d    4
dtype: int64

In [24]:
'b' in obj2

True

### DataFrame
- 表示一种类似电子表格的数据结构
- 每一列都可以包含不同的值类型(数值型, 字符串, 布尔型, 等等)
- 具有行和列索引

<h1, align="center">按国家和年份统计的CO2排放量</h1>

二氧化碳排放源自燃烧化石燃料和水泥制造，包含了在固体、液体和气体燃料消耗以及放空燃烧过程中所产生的二氧化碳

http://data.worldbank.org/indicator/EN.ATM.CO2E.PC/

<h2, align=center>获取数据</h2>

这些数据可以从世界银行(World Bank) [链接](http://data.worldbank.org/indicator/EN.ATM.CO2E.PC/) 或者从 Box [链接](https://ibm.box.com/shared/static/3yzxbbizo49bkl8cnjw15tymzfwkycj4.csv) 上下载

#### 我们在linux下可以使用bash命令 `wget` 从链接处获取 csv 文件

In [ ]:
!wget --output-document /resources/data/co2emissions.csv https://ibm.box.com/shared/static/3yzxbbizo49bkl8cnjw15tymzfwkycj4.csv

<hr>

<h2, align=center>使用 Pandas 导入数据</h2>

#### 导入所需的 `pandas` 库

In [ ]:
import pandas as pd

#### 使用 `pd.read_csv` 导入数据

In [25]:
data = pd.read_csv("C:/Users/Thinkpad/Desktop/co2data.csv", skiprows = 4)

In [26]:
type(data) #Checks the type of object

pandas.core.frame.DataFrame

In [28]:
data

Country Name Country Code                          Indicator Name  \
0           Aruba          ABW  CO2 emissions (metric tons per capita)   
1     Afghanistan          AFG  CO2 emissions (metric tons per capita)   
2          Angola          AGO  CO2 emissions (metric tons per capita)   
3         Albania          ALB  CO2 emissions (metric tons per capita)   
4         Andorra          AND  CO2 emissions (metric tons per capita)   
..            ...          ...                                     ...   
259        Kosovo          XKX  CO2 emissions (metric tons per capita)   
260   Yemen, Rep.          YEM  CO2 emissions (metric tons per capita)   
261  South Africa          ZAF  CO2 emissions (metric tons per capita)   
262        Zambia          ZMB  CO2 emissions (metric tons per capita)   
263      Zimbabwe          ZWE  CO2 emissions (metric tons per capita)   

     Indicator Code      1960      1961      1962      1963      1964  \
0    EN.ATM.CO2E.PC       NaN       NaN       NaN       NaN       NaN   
1    EN.ATM.CO2E.PC  0.046057  0.053589  0.073721  0.074161  0.086174   
2    EN.ATM.CO2E.PC  0.100835  0.082204  0.210531  0.202737  0.213560   
3    EN.ATM.CO2E.PC  1.258195  1.374186  1.439956  1.181681  1.111742   
4    EN.ATM.CO2E.PC       NaN       NaN       NaN       NaN       NaN   
..              ...       ...       ...       ...       ...       ...   
259  EN.ATM.CO2E.PC       NaN       NaN       NaN       NaN       NaN   
260  EN.ATM.CO2E.PC  0.683679  0.494324  0.710130  0.525293  0.644143   
261  EN.ATM.CO2E.PC  5.727221  5.832621  5.887170  5.961336  6.332342   
262  EN.ATM.CO2E.PC       NaN       NaN       NaN       NaN  0.946606   
263  EN.ATM.CO2E.PC       NaN       NaN       NaN       NaN  1.034903   

         1965  ...       2010       2011       2012      2013      2014  2015  \
0         NaN  ...  24.670529  24.507516  13.157722  8.353561  8.410064   NaN   
1    0.101285  ...   0.289988   0.406424   0.345149  0.310341  0.293946   NaN   
2    0.205891  ...   1.244092   1.252681   1.330219  1.253776  1.290307   NaN   
3    1.166099  ...   1.578574   1.803715   1.692908  1.749211  1.978763   NaN   
4         NaN  ...   6.122595   5.867410   5.916884  5.901775  5.832906   NaN   
..        ...  ...        ...        ...        ...       ...       ...   ...   
259       NaN  ...        NaN        NaN        NaN       NaN       NaN   NaN   
260  0.686312  ...   1.011975   0.826044   0.762823  1.013900  0.878996   NaN   
261  6.616544  ...   9.256681   9.048936   8.872523  8.686590  8.979062   NaN   
262  1.096876  ...   0.197823   0.209458   0.253506  0.265078  0.292412   NaN   
263  1.166242  ...   0.612528   0.741686   0.594152  0.874563  0.884721   NaN   

     2016  2017  2018  Unnamed: 63  
0     NaN   NaN   NaN          NaN  
1     NaN   NaN   NaN          NaN  
2     NaN   NaN   NaN          NaN  
3     NaN   NaN   NaN          NaN  
4     NaN   NaN   NaN          NaN  
..    ...   ...   ...          ...  
259   NaN   NaN   NaN          NaN  
260   NaN   NaN   NaN          NaN  
261   NaN   NaN   NaN          NaN  
262   NaN   NaN   NaN          NaN  
263   NaN   NaN   NaN          NaN  

[264 rows x 64 columns]

<h2, align=center>Dataframe 的特性</h2>

#### 使用 `head` 显示 `data`  的前5行

In [29]:
data.head()

Country Name Country Code                          Indicator Name  \
0        Aruba          ABW  CO2 emissions (metric tons per capita)   
1  Afghanistan          AFG  CO2 emissions (metric tons per capita)   
2       Angola          AGO  CO2 emissions (metric tons per capita)   
3      Albania          ALB  CO2 emissions (metric tons per capita)   
4      Andorra          AND  CO2 emissions (metric tons per capita)   

   Indicator Code      1960      1961      1962      1963      1964      1965  \
0  EN.ATM.CO2E.PC       NaN       NaN       NaN       NaN       NaN       NaN   
1  EN.ATM.CO2E.PC  0.046057  0.053589  0.073721  0.074161  0.086174  0.101285   
2  EN.ATM.CO2E.PC  0.100835  0.082204  0.210531  0.202737  0.213560  0.205891   
3  EN.ATM.CO2E.PC  1.258195  1.374186  1.439956  1.181681  1.111742  1.166099   
4  EN.ATM.CO2E.PC       NaN       NaN       NaN       NaN       NaN       NaN   

   ...       2010       2011       2012      2013      2014  2015  2016  2017  \
0  ...  24.670529  24.507516  13.157722  8.353561  8.410064   NaN   NaN   NaN   
1  ...   0.289988   0.406424   0.345149  0.310341  0.293946   NaN   NaN   NaN   
2  ...   1.244092   1.252681   1.330219  1.253776  1.290307   NaN   NaN   NaN   
3  ...   1.578574   1.803715   1.692908  1.749211  1.978763   NaN   NaN   NaN   
4  ...   6.122595   5.867410   5.916884  5.901775  5.832906   NaN   NaN   NaN   

   2018  Unnamed: 63  
0   NaN          NaN  
1   NaN          NaN  
2   NaN          NaN  
3   NaN          NaN  
4   NaN          NaN  

[5 rows x 64 columns]

#### 使用 `head` 获取前2行

In [30]:
data.head(2)

Country Name Country Code                          Indicator Name  \
0        Aruba          ABW  CO2 emissions (metric tons per capita)   
1  Afghanistan          AFG  CO2 emissions (metric tons per capita)   

   Indicator Code      1960      1961      1962      1963      1964      1965  \
0  EN.ATM.CO2E.PC       NaN       NaN       NaN       NaN       NaN       NaN   
1  EN.ATM.CO2E.PC  0.046057  0.053589  0.073721  0.074161  0.086174  0.101285   

   ...       2010       2011       2012      2013      2014  2015  2016  2017  \
0  ...  24.670529  24.507516  13.157722  8.353561  8.410064   NaN   NaN   NaN   
1  ...   0.289988   0.406424   0.345149  0.310341  0.293946   NaN   NaN   NaN   

   2018  Unnamed: 63  
0   NaN          NaN  
1   NaN          NaN  

[2 rows x 64 columns]

In [31]:
data.head(n=1)

Country Name Country Code                          Indicator Name  \
0        Aruba          ABW  CO2 emissions (metric tons per capita)   

   Indicator Code  1960  1961  1962  1963  1964  1965  ...       2010  \
0  EN.ATM.CO2E.PC   NaN   NaN   NaN   NaN   NaN   NaN  ...  24.670529   

        2011       2012      2013      2014  2015  2016  2017  2018  \
0  24.507516  13.157722  8.353561  8.410064   NaN   NaN   NaN   NaN   

   Unnamed: 63  
0          NaN  

[1 rows x 64 columns]

### 不记得需要向函数传递什么参数了？可以使用 `?`

In [32]:
#To close help window, press q
? data.head

#### 显示最后3行数据

In [33]:
data.tail(3)

Country Name Country Code                          Indicator Name  \
261  South Africa          ZAF  CO2 emissions (metric tons per capita)   
262        Zambia          ZMB  CO2 emissions (metric tons per capita)   
263      Zimbabwe          ZWE  CO2 emissions (metric tons per capita)   

     Indicator Code      1960      1961     1962      1963      1964  \
261  EN.ATM.CO2E.PC  5.727221  5.832621  5.88717  5.961336  6.332342   
262  EN.ATM.CO2E.PC       NaN       NaN      NaN       NaN  0.946606   
263  EN.ATM.CO2E.PC       NaN       NaN      NaN       NaN  1.034903   

         1965  ...      2010      2011      2012      2013      2014  2015  \
261  6.616544  ...  9.256681  9.048936  8.872523  8.686590  8.979062   NaN   
262  1.096876  ...  0.197823  0.209458  0.253506  0.265078  0.292412   NaN   
263  1.166242  ...  0.612528  0.741686  0.594152  0.874563  0.884721   NaN   

     2016  2017  2018  Unnamed: 63  
261   NaN   NaN   NaN          NaN  
262   NaN   NaN   NaN          NaN  
263   NaN   NaN   NaN          NaN  

[3 rows x 64 columns]

<hr>

<h2, align=center>Dataframe 的特性</h2>

#### 有多少行和多少列?

In [34]:
data.shape #(rows, columns)

(264, 64)

In [35]:
data.describe()

1960        1961        1962        1963        1964        1965  \
count  193.000000  194.000000  196.000000  197.000000  203.000000  203.000000   
mean     2.037282    2.150171    2.241690    2.753812    2.916141    3.035673   
std      4.184849    4.377180    4.717044    8.443484    8.493180    8.706497   
min      0.007984    0.007857    0.008435    0.009336    0.011589    0.011851   
25%      0.183316    0.180620    0.198531    0.199338    0.214492    0.233321   
50%      0.612271    0.636830    0.654542    0.640002    0.765958    0.695949   
75%      1.694988    1.726250    1.939525    1.710527    1.998806    2.190061   
max     36.685183   36.583778   42.360705   99.464612   92.860862   85.458585   

             1966        1967        1968        1969  ...        2010  \
count  203.000000  203.000000  203.000000  203.000000  ...  249.000000   
mean     3.049316    3.116120    3.315619    3.927816  ...    4.847677   
std      8.062852    7.263779    7.187105    9.921855  ...    5.858565   
min      0.013248    0.011791   -0.020098    0.016104  ...    0.024515   
25%      0.242972    0.251838    0.280633    0.320451  ...    0.815799   
50%      0.750375    0.802935    1.004495    1.056845  ...    2.935527   
75%      2.455830    2.923741    3.257972    3.597430  ...    6.642697   
max     78.625153   77.502352   75.967182  101.051663  ...   39.059708   

             2011        2012        2013        2014  2015  2016  2017  2018  \
count  249.000000  251.000000  251.000000  250.000000   1.0   1.0   1.0   1.0   
mean     4.811059    4.955428    4.872777    4.886320   0.0   0.0   0.0   0.0   
std      5.786095    6.155163    5.840759    6.068998   NaN   NaN   NaN   NaN   
min      0.027016    0.030539    0.030365    0.044700   0.0   0.0   0.0   0.0   
25%      0.832929    0.836163    0.866682    0.880427   0.0   0.0   0.0   0.0   
50%      2.951649    3.027053    3.042065    3.091317   0.0   0.0   0.0   0.0   
75%      6.715381    6.694898    6.745239    6.391435   0.0   0.0   0.0   0.0   
max     39.509205   42.860375   36.387918   43.857308   0.0   0.0   0.0   0.0   

       Unnamed: 63  
count          0.0  
mean           NaN  
std            NaN  
min            NaN  
25%            NaN  
50%            NaN  
75%            NaN  
max            NaN  

[8 rows x 60 columns]

#### 列名有哪些?

In [36]:
data.columns

Index(['Country Name', 'Country Code', 'Indicator Name', 'Indicator Code',
       '1960', '1961', '1962', '1963', '1964', '1965', '1966', '1967', '1968',
       '1969', '1970', '1971', '1972', '1973', '1974', '1975', '1976', '1977',
       '1978', '1979', '1980', '1981', '1982', '1983', '1984', '1985', '1986',
       '1987', '1988', '1989', '1990', '1991', '1992', '1993', '1994', '1995',
       '1996', '1997', '1998', '1999', '2000', '2001', '2002', '2003', '2004',
       '2005', '2006', '2007', '2008', '2009', '2010', '2011', '2012', '2013',
       '2014', '2015', '2016', '2017', '2018', 'Unnamed: 63'],
      dtype='object')

#### 第一列的名字是什么?

In [37]:
data.columns[0]

'Country Name'

#### 第一列和第二列的名字是什么?

In [38]:
data.columns[[0,1]]

Index(['Country Name', 'Country Code'], dtype='object')

<hr>

## 复习

### <span style="color: red">轮到你了:</span> 

#### 打印 `data` 的前3行

In [ ]:
## YOUR CODE BELOW



#### 打印第一行和最后一行的名字

In [ ]:
## YOUR CODE BELOW
data.columns[[0,-1]]


<hr>

<h2, align=center>对 Dataframe 求子集</h2>

### 选择列

#### 按名字选择列:

In [ ]:
data['Country Name']

#### 按列号选择列:

In [ ]:
data[data.columns[0]]

#### 选择最后一列:

In [ ]:
data[data.columns[-1]]

#### 按名字选择由多列构成子集

In [ ]:
data[['Country Name', 'Country Code']]

### 选择行

若干种方式:

In [ ]:
data[0:2] #First and second row

In [ ]:
data[:2] 

In [ ]:
data.iloc[[0,2]] #First and third rows

In [ ]:
data[0:2]['Country Name']

In [39]:
data.ix[0:3,1:4] #First row

F:\Anaconda\lib\site-packages\ipykernel_launcher.py:1: FutureWarning: 
.ix is deprecated. Please use
.loc for label based indexing or
.iloc for positional indexing

See the documentation here:
http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#ix-indexer-is-deprecated
  """Entry point for launching an IPython kernel.
F:\Anaconda\lib\site-packages\pandas\core\indexing.py:822: FutureWarning: 
.ix is deprecated. Please use
.loc for label based indexing or
.iloc for positional indexing

See the documentation here:
http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#ix-indexer-is-deprecated
  retval = getattr(retval, self.name)._getitem_axis(key, axis=i)


Country Code                          Indicator Name  Indicator Code
0          ABW  CO2 emissions (metric tons per capita)  EN.ATM.CO2E.PC
1          AFG  CO2 emissions (metric tons per capita)  EN.ATM.CO2E.PC
2          AGO  CO2 emissions (metric tons per capita)  EN.ATM.CO2E.PC
3          ALB  CO2 emissions (metric tons per capita)  EN.ATM.CO2E.PC

#### 选择最后一行

In [40]:
data.iloc[-1]

Country Name                                    Zimbabwe
Country Code                                         ZWE
Indicator Name    CO2 emissions (metric tons per capita)
Indicator Code                            EN.ATM.CO2E.PC
1960                                                 NaN
                                   ...                  
2015                                                 NaN
2016                                                 NaN
2017                                                 NaN
2018                                                 NaN
Unnamed: 63                                          NaN
Name: 263, Length: 64, dtype: object

<h2, align=center>按照条件求子集</h2>

回忆: 有多种逻辑操作符可以用来创建逻辑语句:

In [41]:
1 == 2

False

In [42]:
"Me" != "You"

True

In [43]:
1000 > 1

True

在将一条逻辑语句应用到数组上时，会返回一个由True/False构成的数组，取值对应于该逻辑语句。

In [44]:
import numpy as np
my_range = np.array(range(1,100))
my_range

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34,
       35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51,
       52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68,
       69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85,
       86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [45]:
result = my_range > 50
result

array([False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True])

然后，我们可以使用这个True/False数组来返回只包含原来数组中对应 true 的那些值。

In [46]:
my_range[result]

array([51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

#### 基于单一条件选择行

In [ ]:
data['Country Name']

In [ ]:
#Data where the country name is Albania. Returns True/False
data['Country Name'] == 'Albania'

In [ ]:
data[data['Country Code'] == 'CHN'] #Subset based on condition

#### 基于多重条件选择行

In [ ]:
data[(data['Country Name'] == 'China') & (data['Country Code'] == 'CHN')]

#### 为什么下面的语句不会返回任何符合条件的行?

In [ ]:
data[(data['Country Name'] == 'Canada') & (data['Country Code'] == 'CHN')]

### 按行和列选择数据

下面的代码产生什么结果?

In [47]:
data[['Country Name', 'Country Code', '2010']][16:21]

Country Name Country Code       2010
16         Benin          BEN   0.553283
17  Burkina Faso          BFA   0.125717
18    Bangladesh          BGD   0.406146
19      Bulgaria          BGR   5.964900
20       Bahrain          BHR  23.585519

<hr>

## 复习

### <span style="color: red">轮到你了:</span> 
<h3>查找法国和德国在2010和2011年的人均CO2排放量</h3>

你应该产生像下面这样的输出:

<img src = https://ibm.box.com/shared/static/23drzeu5h2uydwhb0un9qa4jq9yzrjbi.png, width = 300>

In [ ]:
#hint
# data['Country Name']== ??
# data[['Country Name', '2010', '2011']].iloc[[??,??]]

In [ ]:
## YOUR CODE BELOW



<hr>