In [1]:
#http://blog.csdn.net/LY_ysys629/article/details/73695242
#python-pandas-Series和DataFrame数据结构构建

In [2]:
#Series
#Series = 一维数组 + 数据标签（索引）
#Series创建

import pandas as pd 
from pandas import Series,DataFrame

In [3]:
#Series()输入可以是列表，可以是数组（各种numpy数据类型），当不指定索引时，系统自动加上0-(N-1)的整数索引（N为数组大小），还可以是字典类型，字典的键会被当成索引，字典的值会被当做Series的值。
#列表构建Series
obj1 = Series([1,2,3,4])
obj1

0    1
1    2
2    3
3    4
dtype: int64

In [4]:
#字典创建Series
stata = {'a':10,'b':20,'c':30,'d':40}

obj2 = Series(stata)
obj2

a    10
b    20
c    30
d    40
dtype: int64

In [5]:
import numpy as np
#自定义索引
obj3 = Series(np.arange(4),index=['aa','bb','cc','dd'])

obj3

aa    0
bb    1
cc    2
dd    3
dtype: int32

In [6]:
obj1

0    1
1    2
2    3
3    4
dtype: int64

In [7]:
#注意利用Series构建数组时，index不能指定，可以通过先复制，在改变index实现修改原Series的索引
obj4 = Series(obj1,index=['aa','bb','cc','dd'])
obj4

aa   NaN
bb   NaN
cc   NaN
dd   NaN
dtype: float64

In [8]:
#Series 访问

#1）通过索引访问包括索引切片
#2）通过逻辑运算访问
#3）通过.values和.index访问

obj1

0    1
1    2
2    3
3    4
dtype: int64

In [9]:
obj1[0]

1

In [10]:

obj1[1:3]

1    2
2    3
dtype: int64

In [11]:
obj1.values


array([1, 2, 3, 4], dtype=int64)

In [12]:
obj1.index

RangeIndex(start=0, stop=4, step=1)

In [13]:
obj1[obj1>2]#逻辑表达式

2    3
3    4
dtype: int64

In [14]:

#Series 方法和属性以及修改

#方法：isnull、notnull等

obj2

a    10
b    20
c    30
d    40
dtype: int64

In [15]:
obj2['e'] = np.nan

In [16]:
obj2.isnull()

a    False
b    False
c    False
d    False
e     True
dtype: bool

In [17]:

obj2.notnull()

a     True
b     True
c     True
d     True
e    False
dtype: bool

In [18]:
#属性：.values,.index,.name,.indes.name

obj2

a    10.0
b    20.0
c    30.0
d    40.0
e     NaN
dtype: float64

In [19]:

obj2.name = 'dict'

obj2.index.name = 'abcde'

In [20]:
obj2.name

'dict'

In [21]:
obj2.index.name

'abcde'

In [22]:
#修改：包括values和index的修改

#vakues修改
obj3

aa    0
bb    1
cc    2
dd    3
dtype: int32

In [23]:
obj3['aa']=5
obj3

aa    5
bb    1
cc    2
dd    3
dtype: int32

In [24]:
obj3[1:3]=7
obj3

aa    5
bb    7
cc    7
dd    3
dtype: int32

In [25]:
obj3.index = ['one','two','three','four']
obj3

one      5
two      7
three    7
four     3
dtype: int32

In [26]:
#Series小结
#1）列表、字典、数组等都可以转化为Series，但是Series只能复制
#2）Series可以进行索引、切片访问他的values
#3）Series有.values,.index,.name,.indexname属性，还要isnull,notnull等实例方法
#4）Series的.name,.index.name可以通过直接赋值进行修改，.values可以过索引、切片进行修改


#DataFrame
#DataFrame是一个表格型的数据结构，是以一个或多个二维块存放的数据表格（层次化索引），DataFrame既有行索引还有列索引，它有一组有序的列，每列既可以是不同类型（数值、字符串、布尔型）的数据，或者可以看做有Series组成的字典。

#可以输入给DataFrame构造器的数据

#类型	说明
#二维ndarray	数据矩阵，还可以传入行标和列标
#由数组、列表或元组组成的字典	每个序列会变成DataFrame的一列，所有序列的长度必须相同
#Numpy的结构化/记录数组	类似于“又数组组成的字典”
#由Series组成的字典	每个Series会成为一列，如果没有显示指定索引，则个Series的索引会被合并（考虑到数字对齐的情况）成结果的行索引
#由字典组成的字典	各内层字典会成为一列，每个字典的键会被合并成结果的行索引
#字典或Series的列表	各项将会成为DataFrame的一行，字典键或series索引的并集将会成为DataFrame的列表
#由列表或元组组成的列表	类似于“二维ndarray”
#另一个DataFrame	该DataFrame的索引将会被沿用，除非显式指定了其他索引
#Numpy的MaskedArray	类似于“二维ndarray”的情况，只是掩码值在结果DataFrame会变成NA/缺失值


In [27]:
#DataFrame 创建

#字典
dictionary = {'state':['0hio','0hio','0hio','Nevada','Nevada'],
             'year':[2000,2001,2002,2001,2002],
             'pop':[1.5,1.7,3.6,2.4,2.9]}
frame = DataFrame(dictionary)

frame

pop   state  year
0  1.5    0hio  2000
1  1.7    0hio  2001
2  3.6    0hio  2002
3  2.4  Nevada  2001
4  2.9  Nevada  2002

In [28]:
#添加修改
frame['add']=[0,0,0,0,0]
frame

pop   state  year  add
0  1.5    0hio  2000    0
1  1.7    0hio  2001    0
2  3.6    0hio  2002    0
3  2.4  Nevada  2001    0
4  2.9  Nevada  2002    0

In [29]:

#让我们看一下数字对齐

value = Series([1,2,3,4,5,6],index = [0,1,2,3,4,5])

frame['add1'] = value

In [30]:
#frame#多的被切掉

frame['add2'] = value
frame#少的被填上nan

pop   state  year  add  add1  add2
0  1.5    0hio  2000    0     1     1
1  1.7    0hio  2001    0     2     2
2  3.6    0hio  2002    0     3     3
3  2.4  Nevada  2001    0     4     4
4  2.9  Nevada  2002    0     5     5

In [31]:
#DataFrame 切片和索引

#看一下索引和切片
frame.index = ['one','two','three','four','five']
frame

pop   state  year  add  add1  add2
one    1.5    0hio  2000    0     1     1
two    1.7    0hio  2001    0     2     2
three  3.6    0hio  2002    0     3     3
four   2.4  Nevada  2001    0     4     4
five   2.9  Nevada  2002    0     5     5

In [32]:
#frame['two']#不能对行进行关键字索引？
   #KeyError           Traceback (most recent call last)


frame['add']
frame[2:4]

pop   state  year  add  add1  add2
three  3.6    0hio  2002    0     3     3
four   2.4  Nevada  2001    0     4     4

In [33]:
frame.ix['three']#行可以通过索引字段.ix进行获取


pop       3.6
state    0hio
year     2002
add         0
add1        3
add2        3
Name: three, dtype: object

In [34]:
#DataFrame 的方法和属性

frame.name = 'objDataFrame'

frame.name

'objDataFrame'

In [35]:
frame.index

Index([u'one', u'two', u'three', u'four', u'five'], dtype='object')

In [36]:
frame.index.name='frameIndex'
frame.index.name

'frameIndex'

In [37]:
frame.values

array([[1.5, '0hio', 2000L, 0L, 1L, 1L],
       [1.7, '0hio', 2001L, 0L, 2L, 2L],
       [3.6, '0hio', 2002L, 0L, 3L, 3L],
       [2.4, 'Nevada', 2001L, 0L, 4L, 4L],
       [2.9, 'Nevada', 2002L, 0L, 5L, 5L]], dtype=object)

In [38]:
frame.columns

Index([u'pop', u'state', u'year', u'add', u'add1', u'add2'], dtype='object')

In [39]:
frame.add#这种方法最好还是不要用了

<bound method DataFrame.add of             pop   state  year  add  add1  add2
frameIndex                                    
one         1.5    0hio  2000    0     1     1
two         1.7    0hio  2001    0     2     2
three       3.6    0hio  2002    0     3     3
four        2.4  Nevada  2001    0     4     4
five        2.9  Nevada  2002    0     5     5>

In [40]:
frame[2:4]

pop   state  year  add  add1  add2
frameIndex                                    
three       3.6    0hio  2002    0     3     3
four        2.4  Nevada  2001    0     4     4

In [41]:
#DataFrame小结

#1）注意，DataFrame的数字对齐
#2）可以使用列的关键字来索引，行索引需使用索引字段.ix[],可以直接使用切片
#3）DataFrame的几个属性.values,.index,.name,.index.name,.columns


In [42]:
#索引对象
#pandas的索引对象负责管理周标签和其他原数据（比如轴名称等），构建Series和DataFrame时，所用的任何数组或其他序列的标签都会被转化成一个Index。

obj2



abcde
a    10.0
b    20.0
c    30.0
d    40.0
e     NaN
Name: dict, dtype: float64

In [43]:
indexObj2 = obj2.index
indexObj2

Index([u'a', u'b', u'c', u'd', u'e'], dtype='object', name=u'abcde')

In [44]:
indexObj2[2:5]

#indexObj2[1]='FF'#不可修改性，但是可以在构建Series或DataFrame时自定义index
#TypeError          Traceback (most recent call last)


Index([u'c', u'd', u'e'], dtype='object', name=u'abcde')

In [45]:
frame

pop   state  year  add  add1  add2
frameIndex                                    
one         1.5    0hio  2000    0     1     1
two         1.7    0hio  2001    0     2     2
three       3.6    0hio  2002    0     3     3
four        2.4  Nevada  2001    0     4     4
five        2.9  Nevada  2002    0     5     5

In [46]:
'add' in frame.columns

True

In [47]:
'one' in frame.index

True

In [48]:
index1 = obj1.index
index1

RangeIndex(start=0, stop=4, step=1)

In [49]:
index2 = obj3.index
index2

Index([u'one', u'two', u'three', u'four'], dtype='object')

In [50]:
index1.append(index2)

Index([0, 1, 2, 3, u'one', u'two', u'three', u'four'], dtype='object')

In [51]:
index2 = [2,4,6,8]

index1.diff(index2)

d:\Anaconda2\lib\site-packages\ipykernel\__main__.py:3: FutureWarning: diff is deprecated. Use difference instead
  app.launch_new_instance()


Int64Index([0, 1, 3], dtype='int64')

In [52]:
index1.isin(index2)

array([False, False,  True, False], dtype=bool)

In [53]:
index1.unique

<bound method RangeIndex.unique of RangeIndex(start=0, stop=4, step=1)>

In [54]:
#pandas 中主要的index对象

#类	说明
#Index	最返回的Index对象，将轴标签表示为一个由python对象组成的numpy数组
#Int64Index	针对整数的特殊Index
#MultiIndex	“层次化”索引对象，表示单个轴上的多层索引，可以看做由元组组成的数组
#DatetimeIndex	存储纳秒级时间戳（用numpy的datetime64类型表示）
#PeriodIndex	针对Period数据（时间间隔）的特殊Index

In [55]:

#Index的方法和属性
#方法	说明
#append	链接另一个Index对象，产生一个新的Index
#diff	计算差集，并得到一个Index
#intersection	计算交集
#union	计算并集
#isin	计算一个指示该Index各值是否都包含在参数集合中的布尔型数组
#delete	删除索引i处的元素，并得到新的Index
#drop	删除传入的值，并得到新的Index
#insert	将元素插入到索引i处，并得到新的Index
#is_monotonic	当各元素均大于等于前一个元素时，返回true
#is_unique	当Index没有重复值时，返回True
#unique	计算Index中唯一值的数组

In [56]:
#python中已经生成的Series，可合成DataFrame
import pandas as pd
a = pd.Series([1,2,3])
a

0    1
1    2
2    3
dtype: int64

In [57]:
b = pd.Series([4,5,6])
b

0    4
1    5
2    6
dtype: int64

In [58]:
#pandas直接用列表生成dataframe，只能按行生成，
c = pd.DataFrame([a,b])
c

0  1  2
0  1  2  3
1  4  5  6

In [59]:
#如果是字典可以按列生成，比如：
c = pd.DataFrame({'a':a,'b':b})
c

a  b
0  1  4
1  2  5
2  3  6

In [60]:
#pandas中series与dataframe数据类型属性及操作基础
#一）属性

#series    ：.index,.values, .name,.index.name
#dataframe ：.columns, .index,.values

#二）创建方法 
#series: 
#一组数组（列表或元组），series除了一组数据外还包括一组索引（即只有行索引），索引可自行定义也可利用Series(),自动生成索引； 
#dataframe: 
#是表格型数据，既有行索引又有列索引，每列数据可以为不同类型数据（数值、字符串、布尔型值），可利用DataFrame（其他数据，dataframe属性)指定dataframe的属性创建dataframe。


In [61]:
#三）实例 
#3.1 创建series及其属性展示实例


In [62]:
#创建series
import pandas as pd
obj_list=[1,2,3,4]
obj_tuple=(4,5,6,7)
obj_dict={'a':[1,2],'b':[2,3],'c':[3,4],'d':[4,5]}

In [63]:
obj_series_list=pd.Series(obj_list)#通过列表创建series
print "#通过列表创建series"
print obj_series_list

#通过列表创建series
0    1
1    2
2    3
3    4
dtype: int64


In [64]:
#定义属性
obj_series_list.index.name='zimu'
obj_series_list.name='data'

In [65]:
obj_series_tuple=pd.Series(obj_tuple,index=list('abcd'))#通过元组创建series
print "#通过元组创建series"
print obj_series_tuple

#通过元组创建series
a    4
b    5
c    6
d    7
dtype: int32


In [66]:
obj_series_dict=pd.Series(obj_dict)#通过字典创建series
print "#通过字典创建series"
print obj_series_dict

#通过字典创建series
a    [1, 2]
b    [2, 3]
c    [3, 4]
d    [4, 5]
dtype: object


In [67]:
#显示series类型及属性
print type(obj_series_list),obj_series_list.dtype
print obj_series_list.index,obj_series_list.index.name
print obj_series_list.values,obj_series_list.name

<class 'pandas.core.series.Series'> int64
RangeIndex(start=0, stop=4, step=1, name=u'zimu') zimu
[1 2 3 4] data


In [68]:
#3.2创建dataframe及其属性展示实例 
#在构建DataFrame时，最常用的就是先创建一个data，data一般可以是字典和数组，再用a=DataFrame(data)来转换为DataFrame结构。在DataFrame（data）时也可以同时传入index和columns参数，两个参数必须是list列表型

#1)由数组、列表或元组组成的字典：，每个序列变成DataFrame的一列，所有序列的长度必须相同 

#创建dataframe
import pandas as pd
import numpy as np
obj_dict={'a':[1,2],'b':[2,3],'c':[3,4],'d':[4,5]}
obj_dict

{'a': [1, 2], 'b': [2, 3], 'c': [3, 4], 'd': [4, 5]}

In [69]:
obj_dataframe_dict=pd.DataFrame(obj_dict)#通过字典创建dataframe
print "#通过字典创建dataframe"
print obj_dataframe_dict

#通过字典创建dataframe
   a  b  c  d
0  1  2  3  4
1  2  3  4  5


In [70]:
obj_array=np.array([[1,2,3,4],[3,4,5,6]])
obj_array

array([[1, 2, 3, 4],
       [3, 4, 5, 6]])

In [71]:
obj_dataframe_array=pd.DataFrame(obj_array,index=['one','two'])#通过矩阵创建dataframe
print "#通过矩阵创建dataframe"
print obj_dataframe_array


#通过矩阵创建dataframe
     0  1  2  3
one  1  2  3  4
two  3  4  5  6


In [72]:
obj_series_1=pd.Series([11,12,13,14])
obj_series_1

0    11
1    12
2    13
3    14
dtype: int64

In [73]:
obj_series_2=pd.Series([21,22,23,24])
obj_series_2

0    21
1    22
2    23
3    24
dtype: int64

In [74]:
obj_dataframe_series=pd.DataFrame([obj_series_1,obj_series_2])#通过series创建dataframe
print "#通过series创建dataframe"
print obj_dataframe_series

#通过series创建dataframe
    0   1   2   3
0  11  12  13  14
1  21  22  23  24


In [75]:
obj_dataframe_dataframe=pd.DataFrame(obj_dataframe_series,index=[0,1,'one'],columns=[0,1,2,'a'])#通过其他dataframe创建dataframe
print "#通过其他dataframe创建dataframe"
print obj_dataframe_dataframe

#通过其他dataframe创建dataframe
        0     1     2   a
0    11.0  12.0  13.0 NaN
1    21.0  22.0  23.0 NaN
one   NaN   NaN   NaN NaN


In [76]:
#dataframe属性
print obj_dataframe_dataframe.dtypes
print obj_dataframe_dataframe.values
print obj_dataframe_dataframe.columns
print obj_dataframe_dataframe.index

0    float64
1    float64
2    float64
a    float64
dtype: object
[[ 11.  12.  13.  nan]
 [ 21.  22.  23.  nan]
 [ nan  nan  nan  nan]]
Index([0, 1, 2, u'a'], dtype='object')
Index([0, 1, u'one'], dtype='object')


In [77]:

#注意： 
#1）由series构成的dataframe，可以合成原series索引，也可以自定义索引，但索引长度要和dataframe行数一致 
#2）由其他dataframe组成的dataframe，当自定义索引与原来dataframe不一样时，新的dataframe会增加自定义索引行，其values=nan。


In [78]:
#############################
#因为Series和DataFrame用的次数非常多，所以将其引入本地命名空间中会更方便。
#先了解两种主要的数据结构。

import pandas as pd
from pandas import Series,DataFrame

In [79]:
#(1)Series

#Series是一种类似与一维数组的对象，它由一组数据以及一组与之相关的数据便签（即索引）组成，仅由一组数据即可产生最简单的Series。

#例如：
a=Series([9,-3,4,2])
a


0    9
1   -3
2    4
3    2
dtype: int64

In [80]:
#系统会自动为Series数据创建整数索引，可通过Series的values和index属性获取其数组表示形式和索引对象
print Series([9,-3,4,2]).values
print Series([9,-3,4,2]).index
#这与字典型数据的keys(),values(),items()类似。

[ 9 -3  4  2]
RangeIndex(start=0, stop=4, step=1)


In [81]:
#同时我们在创建Series时也可以自定义索引值：
b=Series([9,-3,4,2],index=['a','c','d','b'])

#那么访问Series中的值时可以直接用b['index']的方法，例如可以同时选取多个值。
b['c']
b[['d','a']]

d    4
a    9
dtype: int64

In [82]:
#也可以直接将一个字典型数据a转化为Series数据，Series(a)
#pandas中用NA表示数据缺失，isnull()和notnull()可用于检测缺失数据，用法为：a.isnull(),a.notnull()

#(2)DataFrame

#DataFrame是一个表格型数据，含有一组有序的列，每一列可以是不同的类型值。DataFrame可以看成是由多个Series组成的字典，它们共用一个索引。

#在构建DataFrame时，最最最常用的就是先创建一个data，data一般可以是字典和数组，再用a=DataFrame(data)来转换为DataFrame结构。在DataFrame（data）时也可以同时传入index和columns参数，两个参数必须是列表型。

#1).构建DataFrame最常见的方法是传入一个由等长列表或数组组成的字典：例如：
data={
    'name':['bon','kate','jun','sam'],
    'stature':['102','112','136','90'],
    'grade':['70','76','98','88']
}
data

{'grade': ['70', '76', '98', '88'],
 'name': ['bon', 'kate', 'jun', 'sam'],
 'stature': ['102', '112', '136', '90']}

In [83]:
frame=DataFrame(data)
#DataFrame会自动加上索引，得到的结果为：
frame

grade  name stature
0    70   bon     102
1    76  kate     112
2    98   jun     136
3    88   sam      90

In [84]:
#2).也可以为DataFrame指定索引

frame2=DataFrame(data,columns=['name','grade','stature','birthdate'],index=['one','two','three','four'])
frame2

name grade stature birthdate
one     bon    70     102       NaN
two    kate    76     112       NaN
three   jun    98     136       NaN
four    sam    88      90       NaN

In [85]:
#跟Series中一样若在对应的列中找不到数据，就会产生缺失值NaN.
#3).取值和赋值
#  查看列：可用类似字典的方式获取一个Series(即一个列的值)，如：frame2['name']；
#  查看行：可用索引字段ix来获取某行的值，如：frame2.ix['three']；
#  可用
frame2['birthdate']=1990
#来直接对某一列进行赋值；
frame2

name grade stature  birthdate
one     bon    70     102       1990
two    kate    76     112       1990
three   jun    98     136       1990
four    sam    88      90       1990

In [86]:
#4).删除某一列的值
del frame2['name']
frame2

grade stature  birthdate
one      70     102       1990
two      76     112       1990
three    98     136       1990
four     88      90       1990

In [87]:
#5)将嵌套型字典转化为DataFrame型时，外层的键作为列，内层的键作为行索引例如：
data={
    'newyork':{'2001':51,'2002':76},
    'houston':{'2001':49,'2002':90},
}
DataFrame(data)  #得到结果为：



houston  newyork
2001       49       51
2002       90       76