In [10]:
#创建dataframe
import pandas as pd
import numpy as np
obj_dict={'a':[1,2],'b':[2,3],'c':[3,4],'d':[4,5]}
obj_array=np.array([[1,2,3,4],[3,4,5,6]])
obj_series_1=pd.Series([11,12,13,14])
obj_series_2=pd.Series([21,22,23,24])

In [11]:
obj_dataframe_dict=pd.DataFrame(obj_dict)#通过字典创建dataframe
obj_dataframe_array=pd.DataFrame(obj_array,index=['one','two'])#通过矩阵创建dataframe
obj_dataframe_series=pd.DataFrame([obj_series_1,obj_series_2])#通过series创建dataframe

obj_dataframe_dataframe=pd.DataFrame(obj_dataframe_series,index=[0,1,'one'],columns=[0,1,2,'a'])#通过其他dataframe创建dataframe


In [12]:
print "#通过字典创建dataframe"
print obj_dataframe_dict

#通过字典创建dataframe
   a  b  c  d
0  1  2  3  4
1  2  3  4  5


In [13]:
print "#通过矩阵创建dataframe"
print obj_dataframe_array

#通过矩阵创建dataframe
     0  1  2  3
one  1  2  3  4
two  3  4  5  6


In [14]:
print "#通过series创建dataframe"
print obj_dataframe_series

#通过series创建dataframe
    0   1   2   3
0  11  12  13  14
1  21  22  23  24


In [15]:

print "#通过其他dataframe创建dataframe"
print obj_dataframe_dataframe

#通过其他dataframe创建dataframe
        0     1     2   a
0    11.0  12.0  13.0 NaN
1    21.0  22.0  23.0 NaN
one   NaN   NaN   NaN NaN


In [16]:
#dataframe属性
print obj_dataframe_dataframe.dtypes

0    float64
1    float64
2    float64
a    float64
dtype: object


In [18]:
print obj_dataframe_dataframe.values

[[ 11.  12.  13.  nan]
 [ 21.  22.  23.  nan]
 [ nan  nan  nan  nan]]


In [19]:
print obj_dataframe_dataframe.columns

Index([0, 1, 2, u'a'], dtype='object')


In [20]:
print obj_dataframe_dataframe.index

Index([0, 1, u'one'], dtype='object')


In [6]:
import pandas as pd  
import numpy as np  
df = pd.DataFrame(np.random.randn(3,4) ,columns=list('abcd'))  

In [7]:
print df  


          a         b         c         d
0  1.615262 -1.034500 -0.864813 -0.080294
1  0.931587  0.890096 -0.165275 -0.319187
2  1.009552 -0.235107  0.420049  1.704400


In [8]:
print df.values  

[[ 1.61526189 -1.0344998  -0.86481341 -0.08029427]
 [ 0.93158714  0.89009648 -0.1652748  -0.31918749]
 [ 1.00955223 -0.2351073   0.42004935  1.70440016]]


In [9]:
print df.as_matrix(columns=None)  

[[ 1.61526189 -1.0344998  -0.86481341 -0.08029427]
 [ 0.93158714  0.89009648 -0.1652748  -0.31918749]
 [ 1.00955223 -0.2351073   0.42004935  1.70440016]]


In [3]:
import numpy as np
a = np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [4]:
a[:2]

array([0, 1])

In [5]:
a = [(735355.0,
  9611.7900000000009,
  9556.0200000000004,
  9627.3799999999992,
  9533.2999999999993,
  88062300.0),
 (735358.0,
  9536.3799999999992,
  9529.5,
  9548.1700000000001,
  9407.0900000000001,
  61911600.0)]

In [6]:
a


[(735355.0, 9611.79, 9556.02, 9627.38, 9533.3, 88062300.0),
 (735358.0, 9536.38, 9529.5, 9548.17, 9407.09, 61911600.0)]

In [7]:
a[:2]

[(735355.0, 9611.79, 9556.02, 9627.38, 9533.3, 88062300.0),
 (735358.0, 9536.38, 9529.5, 9548.17, 9407.09, 61911600.0)]

In [2]:
import pandas as pd
data=pd.DataFrame([[1,2,3],[4,5,6]])
data

0  1  2
0  1  2  3
1  4  5  6

In [3]:
print data.drop(0)

   0  1  2
1  4  5  6


In [7]:
df = pd.DataFrame([['NaN', 'NaN'], 
                   ['SD', 'SX'],
                   ['HN', 'HB'], 
                   ['HEN', 'HEN'], 
                   ['SH', 'TJ']], columns=['p1', 'p2'])
df

p1   p2
0  NaN  NaN
1   SD   SX
2   HN   HB
3  HEN  HEN
4   SH   TJ

In [11]:
ex_list = list(df.p1)
ex_list.remove('NaN')
ex_list
df[df.p1.isin(ex_list)]

p1   p2
1   SD   SX
2   HN   HB
3  HEN  HEN
4   SH   TJ

p1   p2
1   SD   SX
2   HN   HB
3  HEN  HEN
4   SH   TJ