In [2]:
import numpy as np
import pandas as pd
from scipy.stats import f, t
import statsmodels.api as sm

F:\Anaconda\lib\importlib\_bootstrap.py:219: RuntimeWarning: numpy.ufunc size changed, may indicate binary incompatibility. Expected 192 from C header, got 216 from PyObject
  return f(*args, **kwds)
F:\Anaconda\lib\importlib\_bootstrap.py:219: RuntimeWarning: numpy.ufunc size changed, may indicate binary incompatibility. Expected 192 from C header, got 216 from PyObject
  return f(*args, **kwds)
F:\Anaconda\lib\importlib\_bootstrap.py:219: RuntimeWarning: numpy.ufunc size changed, may indicate binary incompatibility. Expected 216, got 192
  return f(*args, **kwds)
F:\Anaconda\lib\importlib\_bootstrap.py:219: RuntimeWarning: numpy.ufunc size changed, may indicate binary incompatibility. Expected 192 from C header, got 216 from PyObject
  return f(*args, **kwds)


In [1]:
L = [1,2,3,4,5,6,7,8,9,10,11]

In [2]:
L[-5:]

[7, 8, 9, 10, 11]

In [1]:
7/0.0775

90.3225806451613

In [4]:
42/1.15

36.52173913043479

In [5]:
(1.56/0.06+1.25)/1.11

24.54954954954955

In [6]:
1.25*1.25

1.5625

In [7]:
(1.5625/0.04+1.25)/1.1

36.647727272727266

In [32]:
XX=np.array([[24/5,0,0,0],[0,2,2,1],[0,2,6,3],[0,1,3,4]])*5

In [33]:
X_X=np.linalg.inv(XX)

In [34]:
Xy=np.array([[0],[7],[-7],[-26]])

In [35]:
beta=X_X.dot(Xy)

In [37]:
beta.T.dot(Xy)

array([[55.2]])

In [38]:
beta.T.dot(XX).dot(beta)

array([[55.2]])

In [43]:
Vbeta=0.24*X_X

In [44]:
Vbeta

array([[ 1.00000000e-02,  0.00000000e+00,  0.00000000e+00,
         0.00000000e+00],
       [ 0.00000000e+00,  3.60000000e-02, -1.20000000e-02,
         1.33226763e-18],
       [ 0.00000000e+00, -1.20000000e-02,  1.68000000e-02,
        -9.60000000e-03],
       [ 0.00000000e+00,  0.00000000e+00, -9.60000000e-03,
         1.92000000e-02]])

In [49]:
t.ppf(0.975,20)

2.0859634472658364

In [50]:
R1 = np.array([0,1,1,1])

In [51]:
R1.dot(beta)/(0.24*R1.dot(X_X).dot(R1.T))**0.5

array([-1.1785113])

In [55]:
R2 = np.array([[0,1,0,0],[0,0,1,0],[0,0,0,1]])

In [52]:
r=np.array([[1],[1],[-2]])

In [57]:
(R2.dot(beta)-r).T.dot(np.linalg.inv(0.24*R2.dot(X_X).dot(R2.T))).dot(R2.dot(beta)-r)/3

array([[15.55555556]])

In [58]:
t.ppf(0.95,3,20)

22.353363434801828

In [56]:
(0.24*R2.dot(X_X).dot(R2.T))

array([[ 3.60000000e-02, -1.20000000e-02,  1.33226763e-18],
       [-1.20000000e-02,  1.68000000e-02, -9.60000000e-03],
       [ 0.00000000e+00, -9.60000000e-03,  1.92000000e-02]])

In [59]:
(0.632-0.452)/(0.257**2+0.219**2-2*0.055)**0.5

2.842498988346894

In [60]:
(0.632+0.452-1)/(0.257**2+0.219**2+2*0.055)**0.5

0.17747843196505955

In [61]:
ss = np.array([[1,2],[3,4]])
np.linalg.inv(ss)

array([[-2. ,  1. ],
       [ 1.5, -0.5]])

In [122]:
ddd=pd.read_excel('C:/Users/Thinkpad/Desktop/高级计量/ps2_data.xlsx',index_col=0)

In [123]:
X=ddd.iloc[:,5:10]
y=ddd.iloc[:,0]

In [124]:
X_=X.sub(X.mean(),axis=1)
y_=y-y.mean()

In [125]:
print(sm.OLS(y,sm.add_constant(X)).fit().summary())

                            OLS Regression Results                            
Dep. Variable:                     V2   R-squared:                       0.061
Model:                            OLS   Adj. R-squared:                  0.011
Method:                 Least Squares   F-statistic:                     1.218
Date:                Fri, 11 Oct 2019   Prob (F-statistic):              0.307
Time:                        01:43:46   Log-Likelihood:                -178.35
No. Observations:                 100   AIC:                             368.7
Df Residuals:                      94   BIC:                             384.3
Df Model:                           5                                         
Covariance Type:            nonrobust                                         
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
const          4.4991      0.797      5.643      0.0

In [126]:
print(sm.OLS(y_,sm.add_constant(X_)).fit().summary())

                            OLS Regression Results                            
Dep. Variable:                     V2   R-squared:                       0.061
Model:                            OLS   Adj. R-squared:                  0.011
Method:                 Least Squares   F-statistic:                     1.218
Date:                Fri, 11 Oct 2019   Prob (F-statistic):              0.307
Time:                        01:43:48   Log-Likelihood:                -178.35
No. Observations:                 100   AIC:                             368.7
Df Residuals:                      94   BIC:                             384.3
Df Model:                           5                                         
Covariance Type:            nonrobust                                         
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
const       3.331e-16      0.149   2.24e-15      1.0

In [4]:
DData=pd.read_excel('C:/Users/Thinkpad/Desktop/高级计量/ps2_data.xlsx',index_col=0)

In [7]:
DData['y'] = DData['V9']
DData['x1'] = 1
DData['x2'] = DData['V3']
DData['x3'] = DData['V5']
DData['x4'] = DData['x3']**2
DData['x5'] = DData['V7'].apply(lambda x: 1 if x == 2 else 0 if x == 1 else x)
DData['x6'] = DData['V8'].apply(lambda x: 1 if x == 2 else 0)
DData['x7'] = DData['V8'].apply(lambda x: 1 if x == 3 else 0)
DData['x8'] = DData['V8'].apply(lambda x: 1 if x == 4 else 0)

In [9]:
print(sm.OLS(DData['y'],DData[['x1','x2']]).fit().summary())

                            OLS Regression Results                            
Dep. Variable:                      y   R-squared:                       0.285
Model:                            OLS   Adj. R-squared:                  0.277
Method:                 Least Squares   F-statistic:                     39.00
Date:                Fri, 11 Oct 2019   Prob (F-statistic):           1.09e-08
Time:                        13:50:49   Log-Likelihood:                -288.15
No. Observations:                 100   AIC:                             580.3
Df Residuals:                      98   BIC:                             585.5
Df Model:                           1                                         
Covariance Type:            nonrobust                                         
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
x1            -1.3149      1.540     -0.854      0.3

In [8]:
print(sm.OLS(DData['y'],DData[['x1','x2','x3','x4']]).fit().summary())

                            OLS Regression Results                            
Dep. Variable:                      y   R-squared:                       0.329
Model:                            OLS   Adj. R-squared:                  0.308
Method:                 Least Squares   F-statistic:                     15.70
Date:                Fri, 11 Oct 2019   Prob (F-statistic):           2.20e-08
Time:                        13:50:15   Log-Likelihood:                -284.94
No. Observations:                 100   AIC:                             577.9
Df Residuals:                      96   BIC:                             588.3
Df Model:                           3                                         
Covariance Type:            nonrobust                                         
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
x1            -9.7908      3.781     -2.590      0.0

In [10]:
print(sm.OLS(DData['y'],DData[['x1','x2','x3','x4','x5']]).fit().summary())

                            OLS Regression Results                            
Dep. Variable:                      y   R-squared:                       0.335
Model:                            OLS   Adj. R-squared:                  0.307
Method:                 Least Squares   F-statistic:                     11.99
Date:                Fri, 11 Oct 2019   Prob (F-statistic):           6.31e-08
Time:                        13:51:14   Log-Likelihood:                -284.47
No. Observations:                 100   AIC:                             578.9
Df Residuals:                      95   BIC:                             592.0
Df Model:                           4                                         
Covariance Type:            nonrobust                                         
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
x1            -9.1338      3.845     -2.375      0.0

In [12]:
print(sm.OLS(DData['y'],DData[['x1','x2','x3','x4','x5','x6','x7','x8']]).fit().summary())

                            OLS Regression Results                            
Dep. Variable:                      y   R-squared:                       0.360
Model:                            OLS   Adj. R-squared:                  0.311
Method:                 Least Squares   F-statistic:                     7.387
Date:                Fri, 11 Oct 2019   Prob (F-statistic):           4.98e-07
Time:                        13:51:45   Log-Likelihood:                -282.60
No. Observations:                 100   AIC:                             581.2
Df Residuals:                      92   BIC:                             602.0
Df Model:                           7                                         
Covariance Type:            nonrobust                                         
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
x1            -9.3530      4.029     -2.321      0.0

In [13]:
DData[['y','x1','x2','x3','x4','x5','x6','x7','x8']].describe()

y     x1          x2         x3           x4          x5  \
count  100.000000  100.0  100.000000  100.00000   100.000000  100.000000   
mean     7.911070    1.0   11.580000   22.19000   569.030000    0.070000   
std      5.129953    0.0    3.435348    8.79818   409.960985    0.256432   
min      0.750000    1.0    2.000000    4.00000    16.000000    0.000000   
25%      5.343750    1.0    9.000000   15.00000   225.000000    0.000000   
50%      6.500000    1.0   12.000000   22.00000   484.000000    0.000000   
75%      8.852500    1.0   13.000000   29.00000   841.000000    0.000000   
max     30.000000    1.0   20.000000   40.00000  1600.000000    1.000000   

               x6          x7          x8  
count  100.000000  100.000000  100.000000  
mean     0.270000    0.270000    0.170000  
std      0.446196    0.446196    0.377525  
min      0.000000    0.000000    0.000000  
25%      0.000000    0.000000    0.000000  
50%      0.000000    0.000000    0.000000  
75%      1.000000    1.000000    0.000000  
max      1.000000    1.000000    1.000000