In [1]:
import numpy as np
import pandas as pd
from scipy.stats import f, t
import statsmodels.api as sm

In [2]:
XX=np.array([[29,0,0],[0,50,10],[0,10,80]])

In [13]:
X_X=np.linalg.inv(XX)

In [7]:
(1+10*1/390)/50

0.02051282051282051

In [8]:
4/195

0.020512820512820513

In [9]:
390/5

78.0

In [10]:
1/78

0.01282051282051282

In [11]:
R1=np.array([[0,1,1]])

In [14]:
R1.dot(X_X).dot(R1.T)

array([[0.02820513]])

In [15]:
0.3/((0.02820513*20)**0.5)

0.3994314013601868

In [17]:
t.ppf(0.975,26)

2.055529438642871

In [18]:
104+88+206+144+199+308+211

1260

In [19]:
570-7*16

458

In [25]:
(1425-1260)/54/(1260/500)

1.2125220458553791

In [24]:
f.ppf(0.95,54,500)

1.3628262160979756

In [27]:
X1X1=np.array([[20,20],[20,25]])
X1_X1=np.linalg.inv(X1X1)

In [28]:
X1_X1

array([[ 0.25, -0.2 ],
       [-0.2 ,  0.2 ]])

In [39]:
b1=X1_X1.dot(np.array([[10],[20]]))
b1

array([[-1.5],
       [ 2. ]])

In [42]:
b1.T.dot(np.array([[10],[20]]))

array([[25.]])

In [29]:
X2X2=np.array([[10,10],[10,20]])
X2_X2=np.linalg.inv(X2X2)

In [30]:
X2_X2

array([[ 0.2, -0.1],
       [-0.1,  0.1]])

In [40]:
b2=X2_X2.dot(np.array([[8],[20]]))
b2

array([[-0.4],
       [ 1.2]])

In [45]:
b2.T.dot(np.array([[8],[20]]))

array([[20.8]])

In [31]:
X3X3=np.array([[30,30],[30,45]])
X3_X3=np.linalg.inv(X3X3)
X3_X3

array([[ 0.1       , -0.06666667],
       [-0.06666667,  0.06666667]])

In [41]:
b3=X3_X3.dot(np.array([[18],[40]]))
b3

array([[-0.86666667],
       [ 1.46666667]])

In [50]:
54-b3.T.dot(np.array([[18],[40]]))

array([[10.93333333]])

In [51]:
(10.93333333-5-3.2)/2/((5+3.2)/26)

4.333333328048781

In [48]:
f.ppf(0.95,2,26)

3.3690163594954443

In [2]:
f.ppf(0.95,2,26)

3.3690163594954443

In [6]:
t.ppf(0.975,100)

1.9839715184496334