In [1]:
import numpy as np

In [2]:
x1z = np.array([[-0.5,1.5,0.5,-1],
                [0,2,0,0],
                [0,0,1,0]])

zx1 = x1z.T

In [7]:
x2z = np.array([[2,1,-3,-5],
                [3,0,0,0],
                [0,0,0,0.5]])

zx2 = x2z.T

In [8]:
zz = np.diag([3,2,1,0.5])

In [9]:
zy1 = np.array([[2],
               [1],
               [-3],
               [-5]])
zy2 = np.array([[-0.5],
               [3/2],
               [0.5],
               [-1]])

In [13]:
b1=np.linalg.inv(x1z.dot(np.linalg.inv(zz)).dot(zx1)).dot(x1z).dot(np.linalg.inv(zz)).dot(zy1)
b1

array([[ 4.64],
       [-2.98],
       [-5.32]])

In [14]:
b2=np.linalg.inv(x2z.dot(np.linalg.inv(zz)).dot(zx2)).dot(x2z).dot(np.linalg.inv(zz)).dot(zy2)
b2

array([[-0.07894737],
       [-0.11403509],
       [-2.78947368]])

In [15]:
x1y1 = np.array([[-4],
               [1],
               [-3]])
x2y2 = np.array([[-4],
                 [-1/2],
                 [-1]])

In [17]:
x1x1=np.array([[5,1.5,0.5],
                [1.5,2,0],
                [0.5,0,1]])
x2x2=np.array([[80,2,-5],
                [2,3,0],
                [-5,0,0.5]])

In [25]:
sigma1 = np.linalg.inv(x1z.dot(np.linalg.inv(zz)).dot(zx1))
sigma1

array([[ 0.48, -0.36, -0.24],
       [-0.36,  0.77,  0.18],
       [-0.24,  0.18,  1.12]])

In [26]:
s1 = (80+b1.T.dot(x1x1).dot(b1)-2*b1.T.dot(x1y1))/100
s1

array([[1.787048]])

In [29]:
sigma1*s1

array([[ 0.85778304, -0.64333728, -0.42889152],
       [-0.64333728,  1.37602696,  0.32166864],
       [-0.42889152,  0.32166864,  2.00149376]])

In [34]:
np.diag(sigma1*s1)**0.5

array([0.92616577, 1.17304176, 1.41474159])

In [30]:
sigma2 = np.linalg.inv(x2z.dot(np.linalg.inv(zz)).dot(zx2))
sigma2

array([[ 0.10526316, -0.07017544,  1.05263158],
       [-0.07017544,  0.38011696, -0.70175439],
       [ 1.05263158, -0.70175439, 12.52631579]])

In [31]:
s2 = (5+b2.T.dot(x2x2).dot(b2)-2*b2.T.dot(x2y2))/100
s2

array([[0.00937442]])

In [32]:
sigma2*s2

array([[ 0.00098678, -0.00065785,  0.00986781],
       [-0.00065785,  0.00356338, -0.00657854],
       [ 0.00986781, -0.00657854,  0.11742698]])

In [35]:
np.diag(sigma2*s2)**0.5

array([0.03141308, 0.05969403, 0.34267621])