In [2]:
import numpy as np

In [36]:
x1z = np.array([[2,1],
                [1,0],
                [0,0]]).T

zx1 = x1z.T

In [37]:
x2z = np.array([[2,0,0],
                [3,1,0],
                [0,0,1]]).T

zx2 = x2z.T

In [38]:
zz = np.diag([1,1,1])

In [39]:
# zz = np.array([[5,2,3],
# [2,10,8],
# [3,8,15]])

In [43]:
zy1 = np.array([[2],
               [3],
               [0]])
zy2 = np.array([[2],
               [1],
               [0]])

In [44]:
b1=np.linalg.inv(x1z.dot(np.linalg.inv(zz)).dot(zx1)).dot(x1z).dot(np.linalg.inv(zz)).dot(zy1)
b1

array([[ 3.],
       [-4.]])

In [45]:
b2=np.linalg.inv(x2z.dot(np.linalg.inv(zz)).dot(zx2)).dot(x2z).dot(np.linalg.inv(zz)).dot(zy2)
b2

array([[ 1.],
       [-2.],
       [ 0.]])

array([[ 0.35232384, -0.2113943 ],
       [-0.2113943 ,  0.32683658]])

In [28]:
x1y1 = np.array([[6],
               [4]])
x2y2 = np.array([[6],
                 [6],
                 [7]])

In [29]:
x1x1=np.array([[10,3],
                [3,5]])
x2x2=np.array([[20,3,5],
                [3,10,8],
              [5,8,15]])

In [30]:
sigma1 = np.linalg.inv(x1z.dot(np.linalg.inv(zz)).dot(zx1))
sigma1

array([[ 0.35232384, -0.2113943 ],
       [-0.2113943 ,  0.32683658]])

In [31]:
s1 = (20+b1.T.dot(x1x1).dot(b1)-2*b1.T.dot(x1y1))/25
s1

array([[0.61039729]])

In [32]:
sigma1*s1

array([[ 0.21505752, -0.12903451],
       [-0.12903451,  0.19950016]])

In [33]:
sigma2 = np.linalg.inv(x2z.dot(np.linalg.inv(zz)).dot(zx2))
sigma2

array([[ 0.4934082 , -0.02868652, -0.14916992],
       [-0.02868652,  0.17608643, -0.08435059],
       [-0.14916992, -0.08435059,  0.16137695]])

In [34]:
s2 = (10+b2.T.dot(x2x2).dot(b2)-2*b2.T.dot(x2y2))/25
s2

array([[0.26838379]])

In [35]:
sigma2*s2

array([[ 0.13242276, -0.007699  , -0.04003479],
       [-0.007699  ,  0.04725874, -0.02263833],
       [-0.04003479, -0.02263833,  0.04331096]])