In [15]:
import pandas as pd
import numpy as np

In [7]:
y = [-1.42,2.75,2.10,-5.08,1.49,1.00,0.16,-1.11,
     1.66,-0.26,-4.87,5.94,2.21,-6.87,0.90,1.61,
     2.11,-3.82,-0.62,7.01,26.14,7.39,0.79,1.93,
     1.97,-23.17,-2.52,-1.26,-0.15,3.41,-5.45,
     1.31,1.52,2.04,3.00,6.31,5.51,-15.22,-1.47,
     -1.48,6.66,1.78,2.62,-5.16,-4.71,-0.35,-0.48,1.24,0.69,1.91]

In [8]:
x1 = [-1.65,1.48,0.77,0.67,0.68,0.23,-0.40,-1.13,0.15,-0.63,0.34,0.35,0.79,0.77,-1.04,0.28,0.58,-0.41,-1.78,1.25,0.22,1.25,-0.12,0.66,1.06,-0.66,-1.18,-0.80,-1.32,0.16,1.06,-0.60,0.79,0.86,2.04,-0.51,0.02,0.33,-1.99,0.70,-0.17,0.33,0.48,1.90,-0.18,-0.18,-1.62,0.39,0.17,1.02]

In [9]:
x2 = [-0.67,0.70,0.32,2.88,-0.19,-1.28,-2.72,-0.70,-1.55,-0.74,-1.87,1.56,0.37,-2.07,1.20,0.26,-1.34,-2.10,0.61,2.32,4.38,2.16,1.51,0.30,-0.17,7.82,-1.15,1.77,2.92,-1.94,2.09,1.50,-0.46,0.19,-0.39,1.54,1.87,-3.45,-0.88,-1.53,1.42,-2.70,1.77,-1.89,-1.85,2.01,1.26,-2.02,1.91,-2.23]

In [12]:
pd.DataFrame({'y':y,'x1':x1,'x2':x2,}).to_excel('chp9data.xlsx',index=False)

In [51]:
y = np.array([y]).reshape(-1,1)
x1 = np.array([x1]).reshape(-1,1)
x2 = np.array([x2]).reshape(-1,1)
l = np.array([[1 for i in x1]]).reshape(-1,1)

In [78]:
X = np.array([l,x1,x2]).T[0]
XX = X.T.dot(X)
XX_1 = np.linalg.inv(XX)
Xy = X.T.dot(y)

In [104]:
b = XX_1.dot(Xy)

In [105]:
b

array([[0.19039401],
       [1.13113339],
       [0.37682493]])

In [81]:
y_hat = X.dot(b)

In [97]:
ee = (y - y_hat).T.dot((y - y_hat))
ee_ = y.T.dot(y) - y.T.dot(X.dot(b))
ss = ee/(50-3)

In [110]:
# LS渐进方差
ss*XX_1

array([[ 0.83621222, -0.11545052, -0.04713622],
       [-0.11545052,  0.96550967,  0.05108081],
       [-0.04713622,  0.05108081,  0.19353153]])

In [112]:
e = (y - y_hat)
e2 = e**2

In [121]:
Sigma = np.diag(e2.T[0])

In [123]:
# 怀特
XX_1.dot(X.T.dot(Sigma).dot(X)).dot(XX_1)

array([[ 0.524589  ,  0.07657756,  0.39921812],
       [ 0.07657756,  0.28236567, -0.09160837],
       [ 0.39921812, -0.09160837,  1.14447365]])

In [136]:
Z = np.array([l,x1,x2,x1*x1,x2*x2,x1*x2]).T[0]

In [178]:
theta = np.linalg.inv(Z.T.dot(Z)).dot(Z.T).dot(e2)
theta

array([[-15.3892919 ],
       [  6.01464244],
       [  3.85210952],
       [  0.63369965],
       [ 12.36653952],
       [  8.38187321]])

In [147]:
# nRsquare - 怀特
(1-(e2-Z.dot(theta)).T.dot((e2-Z.dot(theta)))/(e2-e2.mean()).T.dot((e2-e2.mean())))*50

array([[39.14823773]])

In [179]:
(1-(e2-Z.dot(theta)).T.dot((e2-Z.dot(theta)))/(e2-e2.mean()).T.dot((e2-e2.mean())))

array([[0.78296475]])

In [174]:
# pagan nRsquare
pgtheta = np.linalg.inv(X.T.dot(X)).dot(X.T.dot(e2))

(1-(e2-X.dot(pgtheta)).T.dot((e2-X.dot(pgtheta)))/(e2-e2.mean()).T.dot((e2-e2.mean())))*50

array([[14.20873389]])

In [180]:
pgtheta

array([[30.93532912],
       [ 4.37168605],
       [31.76839617]])

In [148]:
# 2step FGLS
lne2 = np.log(e2)

In [181]:
gamma

array([[0.88469897],
       [0.72533694],
       [0.20020115]])

In [161]:
gamma = np.linalg.inv(X.T.dot(X)).dot(X.T).dot(lne2)
e2_hat = np.exp(X.dot(gamma))

In [162]:
Sigma_hat = np.diag(e2_hat.T[0])
Sigma_hat_1 = np.linalg.inv(Sigma_hat)
np.linalg.inv(X.T.dot(Sigma_hat_1).dot(X)).dot(X.T.dot(Sigma_hat_1)).dot(y)

array([[0.16662621],
       [0.77648745],
       [0.847177  ]])